/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSystemRouteImport } from './routes/_layout/system'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutPlayRouteImport } from './routes/_layout/play'
import { Route as LayoutOpeningsRouteImport } from './routes/_layout/openings'
import { Route as LayoutMatchmakingRouteImport } from './routes/_layout/matchmaking'
import { Route as LayoutHistoryRouteImport } from './routes/_layout/history'
import { Route as LayoutAnalysisRouteImport } from './routes/_layout/analysis'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSystemRoute = LayoutSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPlayRoute = LayoutPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutOpeningsRoute = LayoutOpeningsRouteImport.update({
  id: '/openings',
  path: '/openings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutMatchmakingRoute = LayoutMatchmakingRouteImport.update({
  id: '/matchmaking',
  path: '/matchmaking',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHistoryRoute = LayoutHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAnalysisRoute = LayoutAnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analysis': typeof LayoutAnalysisRoute
  '/history': typeof LayoutHistoryRoute
  '/matchmaking': typeof LayoutMatchmakingRoute
  '/openings': typeof LayoutOpeningsRoute
  '/play': typeof LayoutPlayRoute
  '/settings': typeof LayoutSettingsRoute
  '/system': typeof LayoutSystemRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/analysis': typeof LayoutAnalysisRoute
  '/history': typeof LayoutHistoryRoute
  '/matchmaking': typeof LayoutMatchmakingRoute
  '/openings': typeof LayoutOpeningsRoute
  '/play': typeof LayoutPlayRoute
  '/settings': typeof LayoutSettingsRoute
  '/system': typeof LayoutSystemRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/analysis': typeof LayoutAnalysisRoute
  '/_layout/history': typeof LayoutHistoryRoute
  '/_layout/matchmaking': typeof LayoutMatchmakingRoute
  '/_layout/openings': typeof LayoutOpeningsRoute
  '/_layout/play': typeof LayoutPlayRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/system': typeof LayoutSystemRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/analysis'
    | '/history'
    | '/matchmaking'
    | '/openings'
    | '/play'
    | '/settings'
    | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/analysis'
    | '/history'
    | '/matchmaking'
    | '/openings'
    | '/play'
    | '/settings'
    | '/system'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/analysis'
    | '/_layout/history'
    | '/_layout/matchmaking'
    | '/_layout/openings'
    | '/_layout/play'
    | '/_layout/settings'
    | '/_layout/system'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/system': {
      id: '/_layout/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof LayoutSystemRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/play': {
      id: '/_layout/play'
      path: '/play'
      fullPath: '/play'
      preLoaderRoute: typeof LayoutPlayRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/openings': {
      id: '/_layout/openings'
      path: '/openings'
      fullPath: '/openings'
      preLoaderRoute: typeof LayoutOpeningsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/matchmaking': {
      id: '/_layout/matchmaking'
      path: '/matchmaking'
      fullPath: '/matchmaking'
      preLoaderRoute: typeof LayoutMatchmakingRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/history': {
      id: '/_layout/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof LayoutHistoryRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/analysis': {
      id: '/_layout/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof LayoutAnalysisRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAnalysisRoute: typeof LayoutAnalysisRoute
  LayoutHistoryRoute: typeof LayoutHistoryRoute
  LayoutMatchmakingRoute: typeof LayoutMatchmakingRoute
  LayoutOpeningsRoute: typeof LayoutOpeningsRoute
  LayoutPlayRoute: typeof LayoutPlayRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSystemRoute: typeof LayoutSystemRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAnalysisRoute: LayoutAnalysisRoute,
  LayoutHistoryRoute: LayoutHistoryRoute,
  LayoutMatchmakingRoute: LayoutMatchmakingRoute,
  LayoutOpeningsRoute: LayoutOpeningsRoute,
  LayoutPlayRoute: LayoutPlayRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSystemRoute: LayoutSystemRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
